rstudio/shinyapps-package-dependencies

packages/Rglpk/install

Addresses issue https://github.com/rstudio/shinyapps-package-dependencies/issues/9

Add Rglpk support

---

packages/rtiff/install

Addresses issue https://github.com/rstudio/shinyapps-package-dependencies/issues/8

Add support for rtiff

---

packages/V8/install
packages/V8/test.R

Tests pass on vagrant for this install.

libv8-dev install and test for package V8

---

packages/sodium/install
packages/sodium/test.R

add package: sodium

---

packages/rsvg/install
packages/rsvg/test.R

Tested with Docker and returned 'Success'.

Added support for rsvg package.

---

packages/Rsymphony/install
packages/Rsymphony/test.R

Add Rsymphony

---

packages/rDEA/install
packages/rDEA/test.R

Support for rDEA

---

packages/sodium/install
packages/sodium/test.R

Reverts rstudio/shinyapps-package-dependencies#38
Now that the base image is updated to Ubuntu 14.04

Re-add add package sodium

---

packages/Rmpfr/install
packages/Rmpfr/test.R

Support for Rmpfr

---

packages/tkrplot/install

Fix tkrplot install

---

packages/animation/install
packages/animation/test.R

This is an experiment to see if creating video files behaves well.

Install graphicsmagick and libav-tools for the animation package

---

packages/rPython/install

which in turn installs python2.7-dev, but also provides `python-config`

Install python-dev

---

packages/rgeos/install
packages/rgeos/test.R

Install libgeos-dev

---

packages/RSelenium/install
packages/RSelenium/test.R
packages/convertGraph/install
packages/convertGraph/test.R

Install phantomjs for convertGraph and RSelenium

---

packages/udunits2/install
packages/udunits2/test.R

Install udunits2

---

packages/sf/install
packages/sf/test.R

Docker image tests fine on my machine. Great setup, well documented!

add support for package sf

---

packages/tensorflow/install

instead of package manager, because it is going to be faster.

Use latest version of pip

---

packages/rgdal/install
packages/rgdal/test.R

This should address the current incompatibility between rgdal and sf.

Use newer version of libgdal available from PPA

---

packages/gridGraphics/install
packages/gridGraphics/test.R

Support gridGraphics

---

packages/redland/install
packages/redland/test.R

test succeeds.  curious that Dockerfile asks for R 3.3.

installs and tests CRAN redland package, by installing librdf0-dev

---

packages/jqr/install
packages/jqr/test.R

Adds install and test scripts for JQR.

Added support for JQR.

---

packages/animation/install
packages/animation/test.R

adds pdftk as a dependency of `animation` package. Discussed in #110

pdftk added to animation

---

.travis.yml
CONTRIBUTING.md
Makefile
test

This adds the ability to run tests on xenial. All tests are passing as of now on both trusty and xenial (and confirmed via travis).

run tests on xenial

---

packages/tensorflow/install

Previously we hard coded to a particular version.

install the latest version of tensorflow

---

CONTRIBUTING.md
packages/odbc/install
packages/odbc/test.R

EULA terms:
By installing drivers with this tool I hereby acknowledge and agree
that the drivers may only be used with RStudio commercial software and
may not be used on a standalone basis or with other software. Further,
I agree that the drivers are subject to the RStudio end user license
agreement at https://www.rstudio.com/about/eula/ and is "Software"
under such agreement and I agree to comply with all terms and
conditions thereof.
Accept EULA terms [y/n]: y

add odbc support and pro drivers

---

packages/odbc/install

Switch wget to curl

---

packages/sf/test.R

See r-spatial/sf#537 and https://github.com/r-spatial/lwgeom

st_make_valid and st_is_valid extracted to new package

---

packages/sys/install
packages/sys/test.R

Requires libapparmor-dev
Fixes #121

Add sys package

---

packages/gdalUtils/install
packages/gdalUtils/test.R

Which requires the gdal binaries, not just the libraries.
Fixes #120

Add gdalUtils package

---

packages/magick/install

The tests were picking this up from `jq`
Fixes #122 more

Fix adding PPA for imagemagick

---

packages/tesseract/install
packages/tesseract/test.R

For https://github.com/rstudio/shinyapps-package-dependencies/issues/132

Add tesseract support

---

packages/igraph/install
packages/igraph/test.R

Support igraph

---

packages/keyring/install
packages/keyring/test.R

Addresses https://groups.google.com/forum/#!topic/shinyapps-users/J52v7rUIMXc

Add package keyring support

---

packages/keyring/install

Latest version introduced a new dependency upon libsodium-dev
Fixes #164

Fix installer for keyring

---

packages/magick/install

Always run `apt-get update` before `apt-get install`

Fix magick

---

packages/units/install
packages/units/test.R

Add support for units package

---

packages/xslt/install
packages/xslt/test.R

Add support for "xslt" package

---

packages/sys/test.R

left in place, since we may be removing testing functionality
close #196

comment deprecated function

---

Makefile

This should speed up the Travis CI builds

Use image built on Docker Hub

---

Dockerfile.bionic
Dockerfile.xenial

To better reflect shinyapps.io environment which provides it via Connect

Add pandoc to Docker images

---

packages/av/install

Since the ffmpeg-3 PPA was removed.
Fixes #227

Update to always use ffmepg-4 PPA

---

packages/tensorflow/install

fix tensorflow install

---

packages/V8/install

add apt-get update before attempting to install libv8-dev

---

packages/symengine/install
packages/symengine/test.R

Add package dependency for symengine

---

packages/bedr/install
packages/bedr/test.R

Adding support for the bedr package

bedr support

---

Dockerfile.focal

For https://github.com/rstudio/lucid-images-shiny/pull/300.

add zip dependency

---

Dockerfile.jammy

This makes the environment used for testing more accurately match the environment new shinyapps.io applications run under.

Resync dockerfiles

---

Makefile
packages/ragg/install

for more fully-featured emoji
relates to https://github.com/r-lib/ragg/issues/140

add fonts-noto-color-emoji for ragg

---

packages/rBLAST/install
packages/rBLAST/test.R

Include [BLAST](https://blast.ncbi.nlm.nih.gov/Blast.cgi) installation, required for [rBLAST](https://github.com/mhahsler/rBLAST) package

rBLAST support
