rstudio/shinyapps-package-dependencies

packages/sodium/install
packages/sodium/test.R

Reverts rstudio/shinyapps-package-dependencies#34
libsodium-dev is not available on Ubuntu Precise. This will need to wait until we upgrade our image.

Revert "add package: sodium"

---

packages/rPython/install
packages/rPython/test.R

Ubuntu 14.04 image doesn't have libpython2.7-dev and python-config installed, unlike Ubuntu 12.04

Add rPython installer

---

.travis.yml
CONTRIBUTING.md
Dockerfile
Makefile

This should fix the travis-ci build without us needing to release official RStudio Docker images for R, yet.

Add Dockerfile for self-contained testing

---

packages/RODBC/install
test

libmyodbc and tdsodbc do not add themselves to the odbcinst.ini file by default.
Adjust their selections and reconfigure the packages.
The odbc-postgresql package _does_ add itself.
We should migrate this change into the base images and once those roll out remove it from here.
Fixes [#127300831] and https://groups.google.com/d/msg/shinyapps-users/t3_7oZK65ik/xIYJiseDEgAJ

Fix unixodbc configuration for MySQL

---

packages/Rsymphony/install
packages/Rsymphony/test.R
test

It has an additional requirement on the CGL library.
Adjust how we run the tests to always perform the package install and test it's result, instead of relying upon `test.R` to perform the install.

The Rsymphony install was failing unnoticed

---

packages/sf/install
packages/sf/test.R

This PR adds liblwgeom, which is automatically linked to by sf >= 0.4-0. It is not available on CRAN binary builds, but many (linux and OSX) users install this package themselves, and build sf from source. It's only a small additional dependency, after those we already have for sf.

add support for liblwgeom (needed by st_make_valid)

---

packages/tensorflow/install
packages/tensorflow/test.R

Pypi has a release candidate for 1.2.0, but not 1.1.0

Support for tensorflow 1.1.0

---

packages/tensorflow/install

The default backend implementation for the keras package now requires the keras python package (i.e. apps using keras master will break until this is merged and deployed).

install keras as part of tensorflow dependencies

---

packages/sodium/install

The sodium install script currently breaks apt-get on xenial because it adds a repository that doesn't exist which causes `apt-get update` to exit non-zero.
If you go to the [repo](http://ppa.launchpad.net/chris-lea/libsodium/ubuntu/dists), you will see the only distributions supported is `vivid`, `precise`, and `trusty`.
The change creates a "whitelist" of supported distributions and only adds the repo if its a supported distro for that machine.

[Sodium] Dont break xenial

---

packages/magick/install

The version of imagemagick on Ubuntu Trusty and Xenial is pretty outdated and has tons of issues, some security problems as well.
This PPA has build of the latest stable version from Debian/Ubuntu, backported to Trusty and Xenial. I highly recommend to use this version on the server.

update imagemagick from PPA

---

packages/tensorflow/install

tensorflow v1.5 is being built on ubuntu 16.04 containers so may have glibc version issues with ubuntu 14.04. from their release notes:
> Our Linux binaries are built using ubuntu 16 containers, potentially introducing glibc incompatibility issues with ubuntu 14.

force use of tensorflow v1.4.1

---

packages/tensorflow/install

Previously was hard-coded to 1.4.1 to avoid issues with tensorflow binaries built on 16.04. This decision appears to have been reverted so more recent binaries should work.

Install the latest version of tensorflow

---

packages/gdalUtils/install

It depends upon `rgdal`, which requires a higher minimum version
of GDAL than what is in the base docker image. Our `rgdal` installer
does the right thing, but we don't trigger additional install scripts
during testing.

Fix the gdalUtils install

---

packages/animation/install
packages/animation/test.R

I've added x264 to the animation install as it is a common encoder for mp4 formats in Linux.  I have added an additional test to the `test.R` so that it will execute with that codec.  The x265 codec is also commonly used, so that was added as well.  @yihui

added x264 to animation install

---

packages/animation/install

- Need to perform `apt-get update` before `apt-get install`
- Install libmagick++-dev even though `animation` depends upon `magick`
The test framework in this repo does not traverse the dependency graph.

Fix animation install

---

packages/redland/test.R
packages/tensorflow/install
packages/tensorflow/test.R

The Travis builds for the two latest PRs (#216 and #220) have failed because of [packages/redland/test.R](https://github.com/rstudio/shinyapps-package-dependencies/blob/master/packages/redland/test.R) which needs to be updated after https://github.com/ropensci/redland-bindings/issues/79.
Here is a PR to fix this test. IMO, it should be merged ASAP and before the awaiting PR.
This closes ropensci/redland-bindings#83

Fix tests for redland and tensorflow packages

---

packages/pagedown/install
packages/pagedown/test.R
packages/websocket/install
packages/websocket/test.R

Hi,
Following [this question](https://community.rstudio.com/t/error-after-using-pagedown-to-generate-a-pdf-from-html-in-a-shinyapp/45999?u=rlesur) on RStudio Community, here is a PR to add the support for the [pagedown](https://cran.r-project.org/package=pagedown) package on shinyapps.io.
I've locally tested against xenial and bionic.
I want to warn you that I had to add a Pandoc installation step to pass a basic functional test. I was surprised because I thought that Pandoc was already installed on shinyapps.io. Tell me if I must remove this step.
Another point: pagedown depends on the websocket package.  
For the bionic image, the websocket package installation failed because `libssl-dev` was not installed.
For the xenial image, the websocket package was correctly installed.

add packages websocket & pagedown support

---

packages/lwgeom/test.R

Neither the current CRAN version and current GitHub are actually installable
(for different reasons) so test against an older CRAN version for now.

Allow lwgeom to pass test

---

packages/gert/install
packages/gert/test.R

`usethis` recently began depending on `gert` which will not function on ubuntu xenial without a more-recent version of `libgit2`
relates to (and once deployed should resolve the underlying issue in): https://github.com/rstudio/rsconnect/issues/473

add cran-libgit2 ppa for gert install

---

CHANGELOG.md
packages/RSelenium/test.R
packages/ragg/install
packages/rtiff/install

**Remove geckodriver from RSelenium test**
Sometime in the last 9 months geckodriver releases started including *.tar.gz.asc files, which is breaking the download.  See https://github.com/mozilla/geckodriver/releases/ Rather than fix that, just don't use geckodriver
**Install extra requirements for ragg**
There are a couple of new requirements for ragg it seems.
**Remove rtiff**
rtiff was removed from cran on jan 20th 2021:

Fix failing tests

---

Dockerfile.xenial

This is to fix:
```
***** TESTING...
/opt/R/4.0.4/lib/R/bin/exec/R: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory
ChemmineOB... FAILED
Makefile:14: recipe for target 'test-all-xenial' failed
make: *** [test-all-xenial] Error 127
```

add libpcre2-dev to the image

---

CONTRIBUTING.md
packages/magick/install
packages/magick/test.R

See https://www.kb.cert.org/vuls/id/332928/
Enable features on focal since ghostscript is new enough
Fixes #286

Enable image magick ghostscript features

---

packages/pagedown/install
packages/pagedown/test.R

This PR proposes to install Chrome instead of Chromium to support `pagedown::chrome_print()`.
Until bionic, Chromium is available as a deb file. However since disco, Chromium is only distributed as a snap package but `snapd` does not work in containers.  
The most simple workaround is to use Chrome instead of Chromium.
FYI, https://github.com/rstudio/shinyapps-package-dependencies/pull/291/commits/8a47293beeb1e380119df7537bdc16eeda554cdd re-introduces a functional test that was removed by https://github.com/rstudio/shinyapps-package-dependencies/pull/220/commits/3bdedd10a4dcfc2d1dcc417ce25397a43de2cb0c (#290 would have been detected by such a test).  
Tell me whether you prefer that I remove it again.
Fix #290

[pagedown] use Google Chrome instead of Chromium

---

packages/tesseract/install
packages/tesseract/test.R

The tesseract package uses training data that is language specific. The current support for shinyapp includes training data for documents written in English (linux package 'tesseract-ocr-eng'), but no other languages. I need to OCR documents in French, so I add the French language support, intalling the linux package 'tesseract-ocr-fra'. Adding support for the most common languages could be useful (such as `tesseract-ocr-spa` for spanish, see [here the list of supported languages](https://tesseract-ocr.github.io/tessdoc/Data-Files-in-different-versions.html)).

Expand package tesseract support include French language

---

.travis.yml
packages/arrow/install
packages/arrow/test.R

There is more users adopting and/or trying out the R bindings of the Apache Arrow Framework. While the package as such installs nicely on shinyapps.io, it would be great to get snappy compression enabled. Snappy Compression seems to be the default for parquet files. 
cf. https://community.rstudio.com/t/r-shiny-server-arrow/125384/1

add snappy support for arrow

---

packages/pagedown/test.R

the existing file is causing total line length limits to be reached in travisci

use a smaller file for testing pagedown pdf

---

.travis.yml
packages/magick/install

@dcaud kindly [opened another PR](https://github.com/rstudio/shinyapps-package-dependencies/pull/321) to adjust the imagemagick policy to enable larger amounts of memory to be used.
After working through the changes required, looking at [imagemagick policy docs](https://imagemagick.org/script/security-policy.php) and having a side conversation with @jeroen about the expectations I think it's best to instead remove the policy altogether.
When magick support was [first added](https://github.com/rstudio/shinyapps-package-dependencies/commit/cc4b25f1a0c87c08dc9fb78409cfa7d12736d44f) to shinyapps.io, the policy installed by the debian package was [far less restrictive](https://salsa.debian.org/debian/imagemagick/-/blob/ca7fe0456001c891bf074890dc3b920154c95ecf/config/policy.xml) (eg. it was not …

remove the debian imagemagick default policy file

---

packages/RSelenium/test.R

It looks like RSelenium is failing to run correctly. The error looks similar to this:
https://github.com/ropensci/RSelenium/issues/264
Since the solution there is to remove a file from chrome, this change will skip the chrome install entirely.

Fix the rselenium tests

---

packages/lwgeom/install

installing of devtools is failing with this error
```
--------------------------- [ANTICONF] --------------------------------
Configuration failed to find the harfbuzz freetype2 fribidi library. Try installing:
* deb: libharfbuzz-dev libfribidi-dev (Debian, Ubuntu, etc)
* rpm: harfbuzz-devel fribidi-devel (Fedora, EPEL)
* csw: libharfbuzz_dev libfribidi_dev (Solaris)
* brew: harfbuzz fribidi (OSX)
If harfbuzz freetype2 fribidi is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a harfbuzz freetype2 fribidi.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: …
```

fix the lwgeom install

---

CODEOWNERS

In combination with branch protection rules on (the newly renamed) `main` branch, will ensure someone has approved any PRs submitted from the public.

Make rstudio/hosted owner of *

---

.github/workflows/main.yml
CHANGELOG.md
packages/rgdal/UNSUPPORTED
packages/rgeos/UNSUPPORTED
test
test-list.sh

This allows us to leave package installation scripts present in this repo for users who may want to rebuild old projects with pinned old versions of the package, while providing an escape hatch for CI that would otherwise fail trying to download a current version of an archived package.
Fixes #364

Add convention to mark a package unsupported

---

.github/workflows/main.yml
CONTRIBUTING.md
packages/magick/install
packages/magick/test.R

The debian default policy for ImageMagick prevents basic stuff like outputting to a PDF.
We'll remove this from our base environment in time as well, but fixing here will be faster / more lightweight.

Add back ImageMagick, just rm debian policy

---

packages/RSelenium/install

phantomjs package is also no longer included in ubuntu apt repo -- and the `RSelenium` developer [notes that support for it is suspended.

RSelenium no longer depends on phantomjs.

---

packages/archive/install
packages/archive/test.R

Hello,
As per @stevenolen 's suggestion, this attempts to allow `archive` to be available. Should resolve #358. Passed docker test.

Add archive support

---

packages/archive/install

Hello, I am getting a deploy error 
The following additional packages will be installed:
libarchive13
Suggested packages:
lrzip
The following NEW packages will be installed:
libarchive-dev
The following packages will be upgraded:
libarchive13
1 upgraded, 1 newly installed, 0 to remove and 131 not upgraded.
Need to get 950 kB of archives.
After this operation, 2195 kB of additional disk space will be used.
Do you want to continue? [Y/n]
I think this pr would resolve it.

libarchive required for archive pkg from CRAN -Issue #358
